### ISSUE TITLE
Save settings is a scam

### ISSUE THREAD

**Issue by mabnz** [tmorris-ftnt/ztptool#12]
Save settings dialog button saves all settings bar the password. When performing repeated testing, this is difficult to reconcile. The password can be saved in plaintext in settings.json but this is not obvious.

Desired behaviour: Prompt to offer saving an obfuscated form of the password in settings.json.

**Comment by tmorris-ftnt** [comment]
Added the option to save the password via a prompt after clicking Save Settings. 

It is saved in plain text, no obfuscation has been added.
