### ISSUE TITLE
Model Device version hardcoded to 6.2

### ISSUE THREAD

**Issue by benwai** [tmorris-ftnt/ztptool#16]
Hi tmorris,

First of all thank you for your great work.
I used your tool for a demo last week and it works great ;-).
I just had to do a slight change on the ztptool.py code, on the lines 527-528 the model device is hardcoded to 6.2 and thus we are unable to deploy device in a 6.4 adom.
Is it possible to change your code in order to use the adom version or the device version in the excel file to select the right model device version?

Thanks

Benoit

**Comment by tmorris-ftnt** [comment]
Sure thing, i'll try to make it so that is uses the device version of the ADOM.

**Comment by benwai** [comment]
thanks a lot tmorris!

**Comment by tmorris-ftnt** [comment]
Code has been updated on github and will be included in next build.

**Comment by tmorris-ftnt** [comment]
included in v1.0.14
