### ISSUE TITLE
Feature Request: Cert Templates -> Generate

### ISSUE THREAD

**Issue by hwchaos** [tmorris-ftnt/ztptool#17]
Hi,

great tool. Any chance you could implement the execution of a certificate template?

exec /securityconsole/sign/certificate/template in the api

This is the only thing I am missing and afaik I can't request a certificate (scep) via CLI Template.

Regards
Manuel

**Comment by tmorris-ftnt** [comment]
Sure thing, I will add an optional field called `Cert_Template` this will be executed against the device before the initial CLI template push.

**Comment by hwchaos** [comment]
Great

Thank you very much

**Comment by tmorris-ftnt** [comment]
included in v1.0.14
