### ISSUE TITLE
Import Device fails at Quick install

### ISSUE THREAD

**Issue by weardj** [tmorris-ftnt/ztptool#19]
Whenever I import the excel sheet with the ZTP tool, it fails at the "Quick install device settings". It appears to create the metafields within FortiManager, but they never get applied to the model devices. See the attached screenshot. 

Relevant information: Fortimanager and FortiGates are running 6.4.5, ZTP-Tool is v1.0.14alpha. 

![Capture](https://user-images.githubusercontent.com/1319795/120508411-b1796b00-c395-11eb-9528-c8f3a927a7a6.PNG)

**Comment by tmorris-ftnt** [comment]
Can you share the content of Branch_Setup CLI template?

Normally this will happen if there is an error in the CLI template, will it install to the device if you do these steps manually?

**Comment by tmorris-ftnt** [comment]
Issue was in CLI template
